name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        dockerfile: 
          - 9000/jre8/Dockerfile
          - 9000/jdk8/Dockerfile
          - 9000/jre11/Dockerfile
          - 9000/jdk11/Dockerfile
          - 9000/jre14/Dockerfile
          - 9000/jdk14/Dockerfile
          - 9000/jre15/Dockerfile
          - 9000/jdk15/Dockerfile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: verify diffs
      run: ./update.sh && git diff --quiet HEAD
    - name: Build all the things
      run: docker build -< ${{ matrix.dockerfile }}

