name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        dockerfile:
          - 9.2/jdk8/Dockerfile
          - 9.2/jdk11/Dockerfile
          - 9.2/jdk17/Dockerfile
          - 9.2/jre8/Dockerfile
          - 9.2/jre11/Dockerfile
          - 9.3/jdk8/Dockerfile
          - 9.3/jdk11/Dockerfile
          - 9.3/jdk17/Dockerfile
          - 9.3/jre8/Dockerfile
          - 9.3/jre11/Dockerfile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: verify diffs
      run: ./update.sh && git diff --quiet HEAD
    - name: Build all the things
      run: docker build -< ${{ matrix.dockerfile }}
